name: Coverage report
on:
  pull_request:
    branches:
      - master
      - main
jobs:
  coverage:
    permissions:
      checks: write
      pull-requests: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ArtiomTr/jest-coverage-report-action@v2
    with:
      github-token: ${{ secrets.SECRET_TOKEN }}
      coverage-file: ./coverage/report.json
      base-coverage-file: ./coverage/master/report.json
