name: main
on:
  pull_request:
    branches:
      - master
      - main
      - develop
jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@main

      - name: Get branch name base_ref
        run: echo package-version ${{ steps.package-version.outputs.current-version }}

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Run the Dev
        run: npm run dev:server

      - name: Run the Build
        run: npm run build:server

      - name: Run the tests
        run: npm test


      - if: ${{ matrix.node-version == '12.x' }}
        name: Get Coverage for badge
        run: |
          # var SUMMARY = [
          #   '',
          #   '=============================== Coverage summary ===============================',
          #   'Statements   : 32.5% ( 39/120 )',
          #   'Branches     : 38.89% ( 21/54 )',
          #   'Functions    : 21.74% ( 5/23 )',
          #   'Lines        : 31.93% ( 38/119 )',
          #   '================================================================================',
          #   ''
          # ];
          # SUMMARY = SUMMARY.split('\n')[5]; // 'Lines        : 31.93% ( 38/119 )'
          # SUMMARY = SUMMARY.split(':')[1].split('(')[0].trim(); // '31.93%'
          SUMMARY="$(npm test -- --coverageReporters='text-summary' | tail -2 | head -1)"
          TOKENS=($SUMMARY)
          # process.env.COVERAGE = '31.93%';
          echo "COVERAGE=$(echo ${TOKENS[2]})" >> $GITHUB_ENV
          # var REF = 'refs/pull/27/merge.json';
          REF=${{ github.ref }}
          # console.log('github.ref: ' + REF);
          echo "github.ref: $REF"
          # var PATHS = REF.split('/');
          IFS='/' read -ra PATHS <<< "$REF"
          # var BRANCH_NAME = PATHS[1] + '_' + PATHS[2];
          BRANCH_NAME="${PATHS[1]}_${PATHS[2]}"
          # console.log(BRANCH_NAME); // 'pull_27'
          echo $BRANCH_NAME
          # process.env.BRANCH = 'pull_27';
          echo "BRANCH=$(echo ${BRANCH_NAME})" >> $GITHUB_ENV



      - if: ${{ matrix.node-version == '12.x' }}
        name: Create the Badge
        uses: schneegans/dynamic-badges-action@v1.0.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: 0be9f6ac374b7c312b8f08c2322100ec
          filename: index-db-orm_test_coverage_badge_${{ github.base_ref }}_v${{ steps.package-version.outputs.current-version }}.json
          label: Test Coverage
          message: ${{ env.COVERAGE }}
          color: green
          namedLogo: jest

      - if: ${{ matrix.node-version == '12.x' }}
        name: Create CI Passing badage
        uses: schneegans/dynamic-badges-action@v1.0.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: 0be9f6ac374b7c312b8f08c2322100ec
          filename: index-db-orm_develop_badge_${{ github.base_ref }}_v${{ steps.package-version.outputs.current-version }}.json
          label: develop build
          message: passing
          color: green

      - if: ${{ matrix.node-version == '12.x' }}
        name: Create CI Passing badage
        uses: schneegans/dynamic-badges-action@v1.0.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: 0be9f6ac374b7c312b8f08c2322100ec
          filename: index-db-orm_build_badge_${{ github.base_ref }}_v${{ steps.package-version.outputs.current-version }}.json
          label: build
          message: passing
          color: green

      - if: ${{ matrix.node-version == '12.x' }}
        name: Create CI Passing badage
        uses: schneegans/dynamic-badges-action@v1.0.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: 0be9f6ac374b7c312b8f08c2322100ec
          filename: index-db-orm_ci_badge_${{ github.base_ref }}_v${{ steps.package-version.outputs.current-version }}.json
          label: ci
          message: passing
          color: green
          namedLogo: github
